from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    # python urls
    path('py1', views.py1, name='py1'),
    path('py2', views.py2, name='py2'),
    path('py3', views.py3, name='py3'),
    path('py4', views.py4, name='py4'),
    path('py5', views.py5, name='py5'),
    path('py6', views.py6, name='py6'),
    path('py7', views.py7, name='py7'),
    # database urls
    path('Database_connection', views.Database_connection, name='Database_connection'),
    # git urls
    path('Git', views.Git, name='Git'),
    # machine_learning urls
    path('Numpy', views.Numpy, name='Numpy'),
    path('Pandas', views.Pandas, name='Pandas'),
    path('Pandas_plus_1', views.Pandas_plus_1, name='Pandas_plus_1'),
    path('Pandas_plus_2', views.Pandas_plus_2, name='Pandas_plus_2'),
    path('Pandas_plus_3', views.Pandas_plus_3, name='Pandas_plus_3'),
    path('Pandas_plus_4', views.Pandas_plus_4, name='Pandas_plus_4'),
    path('Pandas_cookbook', views.Pandas_cookbook, name='Pandas_cookbook'),
    path('Descriptive', views.descriptive, name='descriptive'),
    # visualization urls
    path('Plotly', views.Plotly, name='Plotly'),
    path('scatter', views.scatter, name='scatter'),
    path('line', views.line, name='line'),
    path('bar', views.bar, name='bar'),
    path('pie', views.pie, name='pie'),
    path('bubble', views.bubble, name='bubble'),
    path('dot', views.dot, name='dot'),
    path('fill_area', views.fill_area, name='fill_area'),
    path('horizontal_bar', views.horizontal_bar, name='horizontal_bar'),
    path('gantt', views.gantt, name='gantt'),
    path('Dash', views.dash, name='dash'),
    # resume
    path('CV', views.resume, name='resume'),
    # WH
    path('Layout', views.layout, name='layout'),
    path('Flow', views.flow, name='flow'),
    path('Rule', views.rule, name='rule'),
    path('Standard', views.standard, name='standard'),
    path('Reverse Logistic', views.reverse_process, name='reverse_process'),
    path('Training Document', views.training, name='training'),
    path('Input Regulation', views.regulation, name='regulation'),
    path('receiving', views.receiving, name='receiving'),
    path('wh_controller', views.wh_controller, name='wh_controller'),
    path('checker', views.checker, name='checker'),
    path('picking', views.picking, name='picking'),
    path('packing', views.packing, name='packing'),
    path('handover', views.handover, name='handover'),
    path('return', views.returning, name='returning'),
    path('PDA', views.pda, name='pda'),
    # LX
    path('flow & procedure', views.flow_procedure, name='flow_procedure'),
    path('Lx_Input Regulation', views.Input_Regulation, name='Input_Regulation'),
    path('Lx_Receiving', views.Lx_Receiving, name='Lx_Receiving'),
    path('Lx_store', views.Lx_store, name='Lx_store'),
    path('Lx_Checking', views.Lx_Checking, name='Lx_Checking'),
    path('Lx_Picking', views.Lx_Picking, name='Lx_Picking'),
    path('Lx_Packaging', views.Lx_Packaging, name='Lx_Packaging'),
    path('Lx_Handover', views.Lx_Handover, name='Lx_Handover'),
    path('Lx_Return', views.Lx_Return, name='Lx_Return'),
    path('allocation', views.allocation, name='allocation'),
    path('wms', views.wms, name='wms'),
    path('3pl', views.vendors, name='vendors'),
    path('location', views.location, name='location'),
    path('priorities', views.priority, name='priority'),
    path('JD', views.jd, name='jd'),
    path('KPIs', views.kpi, name='kpi'),
    path('Planning', views.planning, name='planning'),
    # freelance
    path('transferimg', views.transferimg, name='transferimg'),
    # sql_server urls
    path('Part1', views.part1, name='part1'),
    path('Part2', views.part2, name='part2'),
    path('Part3', views.part3, name='part3'),
    path('Part4', views.part4, name='part4'),
    path('Part5', views.part5, name='part5'),
    path('Part6', views.part6, name='part6'),
    path('Part7', views.part7, name='part7'),
    path('Part8', views.part8, name='part8'),
    path('Part9', views.part9, name='part9'),
    path('Part10', views.part10, name='part10'),
    path('Part11', views.part11, name='part11'),
    path('Part12', views.part12, name='part12'),
    # ielts urls
    path('unit1', views.unit1, name='unit1'),
    path('unit2', views.unit2, name='unit2'),
    path('unit3', views.unit3, name='unit3'),
    path('unit4', views.unit4, name='unit4'),
    path('unit5', views.unit5, name='unit5'),
    path('unit6', views.unit6, name='unit6'),
    path('unit7', views.unit7, name='unit7'),
    path('unit8', views.unit8, name='unit8'),
    path('unit9', views.unit9, name='unit9'),
    path('unit10', views.unit10, name='unit10'),
    path('unit11', views.unit11, name='unit11'),
    path('unit12', views.unit12, name='unit12'),
    path('unit13', views.unit13, name='unit13'),
    path('unit14', views.unit14, name='unit14'),
    path('unit15', views.unit15, name='unit15'),
    path('unit16', views.unit16, name='unit16'),
    path('unit17', views.unit17, name='unit17'),
    path('unit18', views.unit18, name='unit18'),
    path('unit19', views.unit19, name='unit19'),
    path('unit20', views.unit20, name='unit20'),
    path('unit21', views.unit21, name='unit21'),
    path('unit22', views.unit22, name='unit22'),
    path('unit23', views.unit23, name='unit23'),
    path('unit24', views.unit24, name='unit24'),
    path('unit25', views.unit25, name='unit25'),
    path('unit26', views.unit26, name='unit26'),
    path('unit27', views.unit27, name='unit27'),
    path('unit28', views.unit28, name='unit28'),
    path('unit29', views.unit29, name='unit29'),
    path('unit30', views.unit30, name='unit30'),
    path('Voca1', views.voca1, name='voca1'),
    path('Voca2', views.voca2, name='voca2')
]
